# Generated by Django 4.2 on 2026-05-25 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HAC', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='owners',
            name='push_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tenent',
            name='push_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
