# Generated by Django 6.0.5 on 2026-05-26 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HAC', '0002_owners_push_token_tenent_push_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartmenttenantbeds',
            name='idUri',
        ),
        migrations.RemoveField(
            model_name='commercialtenantbeds',
            name='idUri',
        ),
        migrations.RemoveField(
            model_name='tenantbeds',
            name='idUri',
        ),
    ]
