# Generated by Django 6.0.5 on 2026-05-26 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HAC', '0003_remove_apartmenttenantbeds_iduri_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankdetails',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='bank_qr_codes/'),
        ),
    ]
